//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.Data.ImageUpload.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public long FileID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FilePath { get; set; }
        public string UserID { get; set; }
        public string CreationUser { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
